version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  train:
    build:
      context: ./train-service
    container_name: train
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  central:
    build:
      context: ./central-service
    container_name: central
    depends_on:
      - redis
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  gatekeeper:
    build:
      context: ./gatekeeper-service
    container_name: gatekeeper
    ports:
      - "3002:3002"
    volumes:
      - "database:/app"

volumes:
  database: